language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-test npm test

after_success:
  - docker build -t hungvi/multi-client ./client
  - docker build -t hungvi/multi-nginx ./nginx
  - docker build -t hungvi/multi-server ./server
  - docker build -t hungvi/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hungvi/multi-client
  - docker push hungvi/multi-nginx
  - docker push hungvi/multi-server
  - docker push hungvi/multi-worker